name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Get dependencies
      working-directory: pkg/scraping/
      run: go get -v -t -d ./...
    - name: Build
      working-directory: pkg/scraping/
      run: go build -v ./...
    - name: Test
      working-directory: pkg/scraping/
      run: go test -v -cover ./...